# Generated by Django 5.0.4 on 2024-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_tourist',
            field=models.BooleanField(default=False),
        ),
    ]
