# Generated by Django 4.1 on 2024-03-31 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.PositiveIntegerField(help_text='Duration in hours')),
                ('availability', models.DateField(help_text='Available dates for the tour')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='users.userprofile')),
            ],
        ),
    ]
