# Generated by Django 4.1 on 2024-04-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='availability',
        ),
        migrations.AddField(
            model_name='tour',
            name='availability_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='availability_start',
            field=models.DateField(null=True),
        ),
    ]
