# Generated by Django 4.1 on 2024-04-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
