# Generated by Django 5.0.4 on 2024-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_images',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
    ]
