# Generated by Django 5.0.4 on 2024-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_tour_tour_images_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude for the tour location', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(blank=True, help_text='Human-readable location name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude for the tour location', null=True),
        ),
    ]
