# Generated by Django 5.0.4 on 2024-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_tour_latitude_tour_location_tour_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
