# Generated by Django 5.0.4 on 2024-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_tour_availability_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in hours'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(help_text='Human-readable location name', max_length=255, null=True),
        ),
    ]
