# Generated by Django 5.0.4 on 2024-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_tour_duration_alter_tour_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the review is from a verified participant'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If the review is visible to the public'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_equipment',
            field=models.PositiveIntegerField(blank=True, help_text='Rating for the equipment provided', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_guide',
            field=models.PositiveIntegerField(blank=True, help_text="Rating for the guide's knowledge and professionalism", null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_overall',
            field=models.PositiveIntegerField(blank=True, help_text='Overall tour rating', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating_value',
            field=models.PositiveIntegerField(blank=True, help_text='Value for money rating', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='response',
            field=models.TextField(blank=True, help_text="Tour operator's response"),
        ),
        migrations.AddField(
            model_name='review',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the tour', max_length=100),
        ),
        migrations.AddField(
            model_name='tour',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], help_text='Difficulty level of the tour', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='languages',
            field=models.CharField(blank=True, choices=[('ENG', 'English'), ('ARM', 'Armenian'), ('RUS', 'Russian')], help_text='Languages in which the tour is offered', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='max_group_size',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point',
            field=models.CharField(blank=True, help_text='Meeting point for the start of the tour', max_length=255),
        ),
        migrations.AddField(
            model_name='tour',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age required to join the tour', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('full', 'Full'), ('cancelled', 'Cancelled')], default='available', help_text='Current status of the tour', max_length=20),
        ),
    ]
